esphome:
  name: cabcam
  friendly_name: Train Cab Camera
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32s3
    board_build.extra_flags:
      - "-DARDUINO_HW_CDC_ON_BOOT=0"
    # Drop the chip clock from 240MHz down to a much cooler 160MHz or 80MHz
    board_build.f_cpu: 160000000L
    # This explicitly tells ESPHome that Octal PSRAM is present on the board
    board_build.arduino.memory_type: qio_opi

esp32:
  board: seeed_xiao_esp32s3
  variant: esp32s3
  framework:
    type: arduino

psram:
  mode: octal

wifi:
  networks:
    - ssid: ""
      password: ""
      priority: 5
  power_save_mode: none
  output_power: 8.5dB

# Enable logging via the USB Serial link
logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG

# Activates a direct web page stream
esp32_camera_web_server:
  - port: 8080
    mode: stream

esp32_camera:
  name: "Cab View"
  # The exact pinout configuration required for the Sense camera board
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  # Optimised settings for balancing clarity and frame rate
  resolution: 640x480
  max_framerate: 20 fps
  jpeg_quality: 25
  vertical_flip: true
  horizontal_mirror: false
  frame_buffer_count: 1
  brightness: 0
  contrast: 0
